In [1]:
# for everything

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# for random forest

from sklearn.ensemble import RandomForestRegressor

In [2]:
rawdat = pd.read_csv('../1500_samples.csv')
len(rawdat)


dat = rawdat.copy()
dat.tail()


dat = dat[(dat['n_hill1'] == 1000)]

train_dat = dat.sample(frac = 0.7, replace = False, random_state = 0)

test_dat = dat.drop(train_dat.index)

train_X = train_dat[['richness', 'abundance']]
train_Y = train_dat[['mean', 'sd']]


test_X = test_dat[['richness', 'abundance']]
test_Y = test_dat[['mean', 'sd']]

In [3]:
test_results = {}

rf_mean = RandomForestRegressor()
rf_mean.fit(train_X, train_Y['mean'])
test_results['rf_mean_r2'] = rf_mean.score(test_X, test_Y['mean'])

rf_sd = RandomForestRegressor()
rf_sd.fit(train_X, train_Y['sd'])
test_results['rf_sd_r2'] = rf_sd.score(test_X, test_Y['sd'])

In [4]:
test_results

{'rf_mean_r2': 0.998883381123051, 'rf_sd_r2': 0.9959328196199235}

In [9]:
rf_test_preds = test_X.copy()
rf_test_preds['rf_sd'] = rf_sd.predict(test_X)
rf_test_preds['rf_mean'] = rf_mean.predict(test_X)

In [11]:
rf_test_preds.tail()

      richness  abundance      rf_sd     rf_mean
1452       196      12312   7.794963  108.631511
1454       197       3982   9.937566   86.161822
1455       197       7744   8.756653  100.927873
1462       198       3541  10.246768   85.484339
1471       200      11334   8.065017  107.122136

In [10]:
# rf_test_preds.to_csv("random_forest_predictions.csv")

In [39]:
def draw_from_normal(mean, sd):
    draws = np.random.default_rng().normal(mean, sd, 1000)
    return(draws)
    
def sample_a_row(a_row_of_x):
    s = a_row_of_x['richness']
    n = a_row_of_x['abundance']
    draws = draw_from_normal(a_row_of_x['rf_mean'], a_row_of_x['rf_sd'])
    x_samples = {"sampled_hill": draws,
                "richness": np.repeat(s, 1000),
                "abundance": np.repeat(n, 1000)}
    x_samples = pd.DataFrame(data=x_samples)
    return(x_samples)

In [40]:
some_samples = sample_a_row(rf_test_preds[:1 ])
some_samples

    sampled_hill  richness  abundance
0       2.522176         3       3606
0       2.814869         3       3606
0       2.460028         3       3606
0       2.601069         3       3606
0       2.289142         3       3606
..           ...       ...        ...
0       1.382240         3       3606
0       2.242691         3       3606
0       2.684525         3       3606
0       2.671344         3       3606
0       2.590296         3       3606

[1000 rows x 3 columns]

In [84]:
starting_df = pd.DataFrame(sample_a_row(rf_test_preds[:1 ]))

In [85]:
for i in range(1, 3):
    this_df = sample_a_row(rf_test_preds[(i - 1):i])
    this_df = pd.DataFrame(this_df)
    starting_df = pd.concat(starting_df, this_df)

/var/folders/5q/9jwkrxtj2p9fl5xjb60sf6lw0000gn/T/ipykernel_40251/859364542.py:4: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only.
  starting_df = pd.concat(starting_df, this_df)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [81]:
starting_df

    sampled_hill  richness  abundance
0       2.343416         3       3606
0       2.370408         3       3606
0       2.027153         3       3606
0       1.926760         3       3606
0       2.478528         3       3606
..           ...       ...        ...
0       2.422653         3       3606
0       2.168756         3       3606
0       1.831148         3       3606
0       2.058552         3       3606
0       1.886004         3       3606

[1000 rows x 3 columns]

In [57]:
many_samples_df.head()

                                                    0
0        sampled_hill  richness  abundance
0      ...
3        sampled_hill  richness  abundance
0      ...
7        sampled_hill  richness  abundance
0      ...
11       sampled_hill  richness  abundance
0      ...
23       sampled_hill  richness  abundance
0      ...